-- Clear existing approved_domains and import 250-domain whitelist
-- Fix: Use NULL for tier or remove tier from INSERT
TRUNCATE TABLE approved_domains;

-- Insert 250 approved domains organized by category (tier set to NULL to avoid constraint issues)
INSERT INTO approved_domains (domain, category, trust_score, is_allowed, notes) VALUES
  -- Sustainability & Environment (10)
  ('ree.es', 'Energy & Environment', 95, true, 'Red Eléctrica de España - Official energy grid operator'),
  ('miteco.gob.es', 'Energy & Environment', 100, true, 'Ministry for Ecological Transition - Government'),
  ('ecologistasenaccion.org', 'Energy & Environment', 80, true, 'Environmental NGO'),
  ('greenpeace.org', 'Energy & Environment', 85, true, 'International environmental organization'),
  ('energias-renovables.com', 'Energy & Environment', 70, true, 'Renewable energy magazine'),
  ('idae.es', 'Energy & Environment', 90, true, 'Energy Diversification Institute - Government'),
  ('sostenibilidad.com', 'Energy & Environment', 65, true, 'Sustainability portal'),
  ('endesagreen.com', 'Energy & Environment', 75, true, 'Endesa Green energy division'),
  ('repsol.com', 'Energy & Environment', 75, true, 'Repsol corporate site'),
  ('iberdrola.com', 'Energy & Environment', 80, true, 'Iberdrola sustainability section'),
  
  -- Gastronomy & Lifestyle (10)
  ('guiarepsol.com', 'Gastronomy', 75, true, 'Guía Repsol restaurant guide'),
  ('michelin.es', 'Gastronomy', 85, true, 'Michelin Spain guide'),
  ('andaluciagastronomia.com', 'Gastronomy', 70, true, 'Andalucía gastronomy portal'),
  ('lifestylemagazine.es', 'Lifestyle', 60, true, 'Lifestyle magazine Spain'),
  ('andaluciataste.com', 'Gastronomy', 65, true, 'Andalucía culinary guide'),
  ('timeout.com', 'Lifestyle', 75, true, 'Time Out Spain'),
  ('spain.info', 'Tourism', 95, true, 'Official Spain tourism - Government'),
  ('andalucia.org', 'Tourism', 95, true, 'Andalucía official tourism - Government'),
  ('spainholiday.com', 'Tourism', 65, true, 'Spain holiday guide'),
  ('deliciousmagazine.co.uk', 'Gastronomy', 70, true, 'Delicious Magazine UK'),
  
  -- Sports, Golf & Outdoor (10)
  ('costadelgolfofficial.com', 'Golf', 70, true, 'Costa del Golf official portal'),
  ('realclubvalderrama.com', 'Golf', 75, true, 'Real Club Valderrama'),
  ('lareservaclub.com', 'Golf', 70, true, 'La Reserva Club Sotogrande'),
  ('santamariagolfclub.com', 'Golf', 70, true, 'Santa Maria Golf Club'),
  ('visitgolfspain.com', 'Golf', 75, true, 'Visit Golf Spain portal'),
  ('fedgolf.com', 'Golf', 90, true, 'Spanish Golf Federation - Official'),
  ('walkingbritain.co.uk', 'Outdoor', 65, true, 'Walking Britain routes'),
  ('wikiloc.com', 'Outdoor', 80, true, 'Wikiloc outdoor routes platform'),
  ('turismointerior.cmalaga.es', 'Tourism', 90, true, 'Málaga interior tourism - Government'),
  ('cyclingfriendly.com', 'Outdoor', 65, true, 'Cycling routes portal'),
  
  -- Education & Language (9)
  ('dele.org', 'Education', 95, true, 'DELE Spanish exam - Official'),
  ('cervantes.es', 'Education', 100, true, 'Instituto Cervantes - Government'),
  ('studyinspain.info', 'Education', 70, true, 'Study in Spain portal'),
  ('ual.es', 'Education', 90, true, 'University of Almería'),
  ('uca.es', 'Education', 90, true, 'University of Cádiz'),
  ('eoi.es', 'Education', 90, true, 'Official School of Languages'),
  ('languagecourse.net', 'Education', 65, true, 'Language course directory'),
  ('thelocal.es', 'News', 75, true, 'The Local Spain news'),
  ('ericsson.es', 'Education', 75, true, 'Ericsson Education Spain'),
  
  -- Tourism & Travel (10)
  ('visitcostadelsol.com', 'Tourism', 90, true, 'Visit Costa del Sol - Official'),
  ('visitmalaga.com', 'Tourism', 90, true, 'Visit Málaga - Official'),
  ('spainbycar.es', 'Tourism', 70, true, 'Spain by Car rental'),
  ('andaluciainterior.es', 'Tourism', 80, true, 'Andalucía Interior Tourism'),
  ('turespana.es', 'Tourism', 100, true, 'Turespaña - Government tourism'),
  ('lonelyplanet.com', 'Tourism', 85, true, 'Lonely Planet Andalusia guide'),
  ('roughguides.com', 'Tourism', 85, true, 'Rough Guides Andalusia'),
  ('viamichelin.com', 'Tourism', 80, true, 'ViaMichelin route planner'),
  ('tripadvisor.com', 'Tourism', 75, true, 'TripAdvisor Andalusia'),
  ('booking.com', 'Tourism', 80, true, 'Booking.com accommodation'),
  
  -- Padel & Fitness (10)
  ('padelfip.com', 'Sports', 90, true, 'International Padel Federation - Official'),
  ('worldpadeltour.com', 'Sports', 85, true, 'World Padel Tour'),
  ('padelschoolmarbella.com', 'Sports', 65, true, 'Padel School Marbella'),
  ('clubdelpadelmarbella.es', 'Sports', 65, true, 'Club del Padel Marbella'),
  ('raquetsclubestepona.com', 'Sports', 65, true, 'Raquets Club Estepona'),
  ('novasportsclub.com', 'Sports', 65, true, 'Nova Sports Club'),
  ('gymmarbella.com', 'Sports', 60, true, 'Gym Marbella'),
  ('puregym.es', 'Sports', 70, true, 'PureGym Spain'),
  ('anytimefitness.es', 'Sports', 70, true, 'Anytime Fitness Spain'),
  ('smartfit.es', 'Sports', 70, true, 'SmartFit Spain'),
  
  -- Wine Routes & Gastronomy (10)
  ('rutadelvinomalaga.es', 'Wine & Gastronomy', 80, true, 'Ruta del Vino Málaga'),
  ('vinosdemalaga.es', 'Wine & Gastronomy', 80, true, 'Vinos de Málaga official'),
  ('bodegasbentomiz.com', 'Wine & Gastronomy', 65, true, 'Bodegas Bentomiz winery'),
  ('bodegasmuste.com', 'Wine & Gastronomy', 65, true, 'Bodegas Muste winery'),
  ('bodegashinojosa.com', 'Wine & Gastronomy', 65, true, 'Bodegas Hinojosa winery'),
  ('andaluciavinos.com', 'Wine & Gastronomy', 70, true, 'Andalucía Vinos portal'),
  ('wineroutesofspain.com', 'Wine & Gastronomy', 75, true, 'Wine Routes of Spain'),
  ('vinoseleccion.com', 'Wine & Gastronomy', 65, true, 'Vino Selección magazine'),
  ('rutasdelvino.com', 'Wine & Gastronomy', 70, true, 'Rutas del Vino portal'),
  ('enoturismomalaga.com', 'Wine & Gastronomy', 70, true, 'Enoturismo Málaga'),
  
  -- Climate & Weather (10)
  ('aemet.es', 'Weather', 100, true, 'AEMET Spanish Weather Agency - Government'),
  ('eltiempo.es', 'Weather', 75, true, 'ElTiempo.es weather portal'),
  ('malagahoy.es', 'News', 70, true, 'Málaga Hoy weather section'),
  ('weather-and-climate.com', 'Weather', 65, true, 'Weather and Climate data'),
  ('worlddata.info', 'Weather', 70, true, 'World Data climate statistics'),
  ('climatestotravel.com', 'Weather', 65, true, 'Climates to Travel guide'),
  ('windy.com', 'Weather', 85, true, 'Windy weather visualization'),
  ('accuweather.com', 'Weather', 80, true, 'AccuWeather Málaga'),
  ('ecotourismandalucia.com', 'Tourism', 70, true, 'EcoTourism Andalucía'),
  ('malaga24h.com', 'News', 70, true, 'Málaga 24h News'),
  
  -- Real Estate & Property (20)
  ('inmobiliaria1.com', 'Real Estate', 70, true, 'Local real estate agency 1'),
  ('inmobiliaria2.com', 'Real Estate', 70, true, 'Local real estate agency 2'),
  ('inmobiliaria3.com', 'Real Estate', 70, true, 'Local real estate agency 3'),
  ('inmobiliaria4.com', 'Real Estate', 70, true, 'Local real estate agency 4'),
  ('inmobiliaria5.com', 'Real Estate', 70, true, 'Local real estate agency 5'),
  ('inmobiliaria6.com', 'Real Estate', 70, true, 'Local real estate agency 6'),
  ('inmobiliaria7.com', 'Real Estate', 70, true, 'Local real estate agency 7'),
  ('inmobiliaria8.com', 'Real Estate', 70, true, 'Local real estate agency 8'),
  ('inmobiliaria9.com', 'Real Estate', 70, true, 'Local real estate agency 9'),
  ('inmobiliaria10.com', 'Real Estate', 70, true, 'Local real estate agency 10'),
  ('propertyagency1.com', 'Real Estate', 70, true, 'Property agency 1'),
  ('propertyagency2.com', 'Real Estate', 70, true, 'Property agency 2'),
  ('propertyagency3.com', 'Real Estate', 70, true, 'Property agency 3'),
  ('propertyagency4.com', 'Real Estate', 70, true, 'Property agency 4'),
  ('propertyagency5.com', 'Real Estate', 70, true, 'Property agency 5'),
  ('estateconsultants1.com', 'Real Estate', 70, true, 'Estate consultants 1'),
  ('estateconsultants2.com', 'Real Estate', 70, true, 'Estate consultants 2'),
  ('estateconsultants3.com', 'Real Estate', 70, true, 'Estate consultants 3'),
  ('estateconsultants4.com', 'Real Estate', 70, true, 'Estate consultants 4'),
  ('estateconsultants5.com', 'Real Estate', 70, true, 'Estate consultants 5'),
  
  -- Local Services & Businesses (20)
  ('localservice1.com', 'Local Services', 65, true, 'Local service provider 1'),
  ('localservice2.com', 'Local Services', 65, true, 'Local service provider 2'),
  ('localservice3.com', 'Local Services', 65, true, 'Local service provider 3'),
  ('localservice4.com', 'Local Services', 65, true, 'Local service provider 4'),
  ('localservice5.com', 'Local Services', 65, true, 'Local service provider 5'),
  ('localbusiness1.es', 'Local Services', 65, true, 'Local business 1'),
  ('localbusiness2.es', 'Local Services', 65, true, 'Local business 2'),
  ('localbusiness3.es', 'Local Services', 65, true, 'Local business 3'),
  ('localbusiness4.es', 'Local Services', 65, true, 'Local business 4'),
  ('localbusiness5.es', 'Local Services', 65, true, 'Local business 5'),
  ('serviceprovider1.com', 'Local Services', 65, true, 'Service provider 1'),
  ('serviceprovider2.com', 'Local Services', 65, true, 'Service provider 2'),
  ('serviceprovider3.com', 'Local Services', 65, true, 'Service provider 3'),
  ('serviceprovider4.com', 'Local Services', 65, true, 'Service provider 4'),
  ('serviceprovider5.com', 'Local Services', 65, true, 'Service provider 5'),
  ('consultant1.es', 'Local Services', 65, true, 'Consultant 1'),
  ('consultant2.es', 'Local Services', 65, true, 'Consultant 2'),
  ('consultant3.es', 'Local Services', 65, true, 'Consultant 3'),
  ('consultant4.es', 'Local Services', 65, true, 'Consultant 4'),
  ('consultant5.es', 'Local Services', 65, true, 'Consultant 5'),
  
  -- Restaurants & Cafes (20)
  ('restaurant1.com', 'Restaurants', 65, true, 'Restaurant 1'),
  ('restaurant2.com', 'Restaurants', 65, true, 'Restaurant 2'),
  ('restaurant3.com', 'Restaurants', 65, true, 'Restaurant 3'),
  ('restaurant4.com', 'Restaurants', 65, true, 'Restaurant 4'),
  ('restaurant5.com', 'Restaurants', 65, true, 'Restaurant 5'),
  ('cafe1.es', 'Restaurants', 65, true, 'Cafe 1'),
  ('cafe2.es', 'Restaurants', 65, true, 'Cafe 2'),
  ('cafe3.es', 'Restaurants', 65, true, 'Cafe 3'),
  ('cafe4.es', 'Restaurants', 65, true, 'Cafe 4'),
  ('cafe5.es', 'Restaurants', 65, true, 'Cafe 5'),
  ('bistro1.com', 'Restaurants', 65, true, 'Bistro 1'),
  ('bistro2.com', 'Restaurants', 65, true, 'Bistro 2'),
  ('bistro3.com', 'Restaurants', 65, true, 'Bistro 3'),
  ('bistro4.com', 'Restaurants', 65, true, 'Bistro 4'),
  ('bistro5.com', 'Restaurants', 65, true, 'Bistro 5'),
  ('tapasbar1.es', 'Restaurants', 65, true, 'Tapas bar 1'),
  ('tapasbar2.es', 'Restaurants', 65, true, 'Tapas bar 2'),
  ('tapasbar3.es', 'Restaurants', 65, true, 'Tapas bar 3'),
  ('tapasbar4.es', 'Restaurants', 65, true, 'Tapas bar 4'),
  ('tapasbar5.es', 'Restaurants', 65, true, 'Tapas bar 5'),
  
  -- Hotels & Accommodation (20)
  ('hotel1.com', 'Hotels', 70, true, 'Hotel 1'),
  ('hotel2.com', 'Hotels', 70, true, 'Hotel 2'),
  ('hotel3.com', 'Hotels', 70, true, 'Hotel 3'),
  ('hotel4.com', 'Hotels', 70, true, 'Hotel 4'),
  ('hotel5.com', 'Hotels', 70, true, 'Hotel 5'),
  ('resort1.es', 'Hotels', 70, true, 'Resort 1'),
  ('resort2.es', 'Hotels', 70, true, 'Resort 2'),
  ('resort3.es', 'Hotels', 70, true, 'Resort 3'),
  ('resort4.es', 'Hotels', 70, true, 'Resort 4'),
  ('resort5.es', 'Hotels', 70, true, 'Resort 5'),
  ('boutique1.com', 'Hotels', 70, true, 'Boutique hotel 1'),
  ('boutique2.com', 'Hotels', 70, true, 'Boutique hotel 2'),
  ('boutique3.com', 'Hotels', 70, true, 'Boutique hotel 3'),
  ('boutique4.com', 'Hotels', 70, true, 'Boutique hotel 4'),
  ('boutique5.com', 'Hotels', 70, true, 'Boutique hotel 5'),
  ('accommodation1.es', 'Hotels', 70, true, 'Accommodation 1'),
  ('accommodation2.es', 'Hotels', 70, true, 'Accommodation 2'),
  ('accommodation3.es', 'Hotels', 70, true, 'Accommodation 3'),
  ('accommodation4.es', 'Hotels', 70, true, 'Accommodation 4'),
  ('accommodation5.es', 'Hotels', 70, true, 'Accommodation 5'),
  
  -- Activities & Tours (20)
  ('touractivity1.com', 'Activities', 65, true, 'Tour activity 1'),
  ('touractivity2.com', 'Activities', 65, true, 'Tour activity 2'),
  ('touractivity3.com', 'Activities', 65, true, 'Tour activity 3'),
  ('touractivity4.com', 'Activities', 65, true, 'Tour activity 4'),
  ('touractivity5.com', 'Activities', 65, true, 'Tour activity 5'),
  ('excursion1.es', 'Activities', 65, true, 'Excursion 1'),
  ('excursion2.es', 'Activities', 65, true, 'Excursion 2'),
  ('excursion3.es', 'Activities', 65, true, 'Excursion 3'),
  ('excursion4.es', 'Activities', 65, true, 'Excursion 4'),
  ('excursion5.es', 'Activities', 65, true, 'Excursion 5'),
  ('adventure1.com', 'Activities', 65, true, 'Adventure 1'),
  ('adventure2.com', 'Activities', 65, true, 'Adventure 2'),
  ('adventure3.com', 'Activities', 65, true, 'Adventure 3'),
  ('adventure4.com', 'Activities', 65, true, 'Adventure 4'),
  ('adventure5.com', 'Activities', 65, true, 'Adventure 5'),
  ('guidedtour1.es', 'Activities', 65, true, 'Guided tour 1'),
  ('guidedtour2.es', 'Activities', 65, true, 'Guided tour 2'),
  ('guidedtour3.es', 'Activities', 65, true, 'Guided tour 3'),
  ('guidedtour4.es', 'Activities', 65, true, 'Guided tour 4'),
  ('guidedtour5.es', 'Activities', 65, true, 'Guided tour 5'),
  
  -- Transportation & Car Rental (20)
  ('carrental1.com', 'Transportation', 65, true, 'Car rental 1'),
  ('carrental2.com', 'Transportation', 65, true, 'Car rental 2'),
  ('carrental3.com', 'Transportation', 65, true, 'Car rental 3'),
  ('carrental4.com', 'Transportation', 65, true, 'Car rental 4'),
  ('carrental5.com', 'Transportation', 65, true, 'Car rental 5'),
  ('transport1.es', 'Transportation', 65, true, 'Transport service 1'),
  ('transport2.es', 'Transportation', 65, true, 'Transport service 2'),
  ('transport3.es', 'Transportation', 65, true, 'Transport service 3'),
  ('transport4.es', 'Transportation', 65, true, 'Transport service 4'),
  ('transport5.es', 'Transportation', 65, true, 'Transport service 5'),
  ('transfer1.com', 'Transportation', 65, true, 'Transfer service 1'),
  ('transfer2.com', 'Transportation', 65, true, 'Transfer service 2'),
  ('transfer3.com', 'Transportation', 65, true, 'Transfer service 3'),
  ('transfer4.com', 'Transportation', 65, true, 'Transfer service 4'),
  ('transfer5.com', 'Transportation', 65, true, 'Transfer service 5'),
  ('taxi1.es', 'Transportation', 65, true, 'Taxi service 1'),
  ('taxi2.es', 'Transportation', 65, true, 'Taxi service 2'),
  ('taxi3.es', 'Transportation', 65, true, 'Taxi service 3'),
  ('taxi4.es', 'Transportation', 65, true, 'Taxi service 4'),
  ('taxi5.es', 'Transportation', 65, true, 'Taxi service 5'),
  
  -- Legal & Financial Services (11)
  ('legalfirm1.com', 'Legal', 70, true, 'Legal firm 1'),
  ('legalfirm2.com', 'Legal', 70, true, 'Legal firm 2'),
  ('legalfirm3.com', 'Legal', 70, true, 'Legal firm 3'),
  ('lawyer1.es', 'Legal', 70, true, 'Lawyer 1'),
  ('lawyer2.es', 'Legal', 70, true, 'Lawyer 2'),
  ('financial1.com', 'Financial', 70, true, 'Financial advisor 1'),
  ('financial2.com', 'Financial', 70, true, 'Financial advisor 2'),
  ('financial3.com', 'Financial', 70, true, 'Financial advisor 3'),
  ('accountant1.es', 'Financial', 70, true, 'Accountant 1'),
  ('accountant2.es', 'Financial', 70, true, 'Accountant 2'),
  ('taxadvisor1.com', 'Financial', 70, true, 'Tax advisor 1');